# ====================== #
# MGCP Finishing Tool v7 #
# Nat Cagle 2022-07-27   #
# ====================== #
import arcpy
from arcpy import AddMessage as write

#            ____________________________
#           | Runs MGCP Populate F_Code, |
#           | Calculate Default          |
#           | Values, Integrate, and     |
#           | Repair on the proper       |
#           | features for finishing.    |
#      _    /‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾‾
#   __(.)< ‾
#~~~\___)~~~


''''''''' Dictionary Definitions '''''''''

### TRD 4.5.1 f_code update ###
fcode_dict = { 'GB005' : 'Land Aerodrome Area',
				'GB035' : 'Heliport Area',
				'GB065' : 'Water Aerodrome Area',
				'GB230' : 'Aircraft Hangar Area',
				'GB030' : 'Helipad Point',
				'GB065' : 'Water Aerodrome Point',
				'GB230' : 'Aircraft Hangar Point',
				'AM020' : 'Grain Storage Structure Area',
				'AM030' : 'Grain Elevator Area',
				'AM020' : 'Grain Storage Structure Point',
				'AM030' : 'Grain Elevator Point',
				'BH010' : 'Aqueduct Area',
				'BH010' : 'Aqueduct Line',
				'BH010' : 'Aqueduct Point',
				'AL070' : 'Fence Line',
				'AL260' : 'Wall Line',
				'DB010' : 'Steep Terrain Face Line',
				'AQ040' : 'Bridge Area',
				'AQ040' : 'Bridge Line',
				'AL015' : 'General Building Area',
				'AL015' : 'General Building Point',
				'AL020' : 'Built-Up Area Area',
				'AL208' : 'Shanty Town Area',
				'AL020' : 'Built-Up Area Point',
				'BI010' : 'Cistern Point',
				'BA030' : 'Island Area',
				'BA040' : 'Tidal Water Area',
				'BA050' : 'Beach Area',
				'BA010' : 'Land Water Boundary Line',
				'BA050' : 'Beach Point',
				'AT050' : 'Communication Station Area',
				'AT010' : 'Dish Aerial Point',
				'AT045' : 'Radar Station Point',
				'BH135' : 'Rice Field Area',
				'EA010' : 'Crop Land Area',
				'EA040' : 'Orchard Area',
				'EA050' : 'Vineyard Area',
				'EA055' : 'Hop Field Area',
				'BI020' : 'Dam Area',
				'BH165' : 'Spillway Area',
				'BI020' : 'Dam Line',
				'BH165' : 'Spillway Line',
				'BI020' : 'Dam Point',
				'BD100' : 'Structural Pile Area',
				'BD120' : 'Reef Area',
				'BD120' : 'Reef Line',
				'BD100' : 'Structural Pile Point',
				'BD110' : 'Offshore Platform Point',
				'BD130' : 'Hazardous Rock Point',
				'BD180' : 'Wreck Point',
				'AB000' : 'Disposal Site Area',
				'AB010' : 'Recycling Site Area',
				'DB090' : 'Embankment Area',
				'AQ063' : 'Causeway Structure Line',
				'DB070' : 'Cut Line',
				'DB090' : 'Embankment Line',
				'DB071' : 'Cut Line Line',
				'AA010' : 'Extraction Mine Area',
				'AA012' : 'Quarry Area',
				'BH155' : 'Salt Evaporator Area',
				'BH150' : 'Salt Flat Area',
				'AA010' : 'Extraction Mine Point',
				'AA012' : 'Quarry Point',
				'AQ070' : 'Ferry Crossing Line',
				'AQ070' : 'Ferry Crossing Point',
				'EC040' : 'Cleared Way Area',
				'EC060' : 'Forest Clearing Area',
				'BH070' : 'Ford Line',
				'BH070' : 'Ford Point',
				'AH050' : 'Fortification Area',
				'AH050' : 'Fortification Point',
				'EB010' : 'Grassland Area',
				'EB020' : 'Thicket Area',
				'EC010' : 'Cane Area',
				'DA010' : 'Soil Surface Region Area',
				'BB005' : 'Harbour Area',
				'BB090' : 'Dry Dock Area',
				'BB155' : 'Maritime Signal Station Point',
				'AF020' : 'Conveyor Line',
				'BH060' : 'Flume Line',
				'FA090' : 'Geophysical Prospecting Grid Line',
				'BH090' : 'Land Subject to Inundation Area',
				'BH080' : 'Lake Area',
				'BH130' : 'Reservoir Area',
				'BH160' : 'Sabkha Area',
				'DB170' : 'Sand Dunes Area',
				'BJ020' : 'Moraine Area',
				'DB160' : 'Rock Formation Area',
				'DB200' : 'Gully Area',
				'BJ031' : 'Crevasse Area',
				'DB061' : 'Crevice Area',
				'BJ040' : 'Ice Cliff Line',
				'DB110' : 'Geologic Fault Line',
				'DB200' : 'Gully Line',
				'BJ031' : 'Crevasse Line',
				'DB061' : 'Crevice Line',
				'DB100' : 'Esker Line',
				'DB160' : 'Rock Formation Line',
				'BJ060' : 'Ice Peak Point',
				'DB160' : 'Rock Formation Point',
				'BJ030' : 'Glacier Area',
				'BJ100' : 'Snow Field and/or Ice-field Area',
				'AJ010' : 'Circular Irrigation System Area',
				'AK030' : 'Amusement Park Area',
				'AK060' : 'Camp-site Area',
				'AK120' : 'Park Area',
				'AK160' : 'Stadium Area',
				'AK180' : 'Zoo Area',
				'AL030' : 'Cemetery Area',
				'AK040' : 'Sports Ground Area',
				'FA015' : 'Firing Range Area',
				'AI030' : 'Camp Area',
				'AK170' : 'Swimming Pool Area',
				'AK130' : 'Racetrack Line',
				'AQ075' : 'Ice Route Line',
				'AK150' : 'Ski-jump Line',
				'AH070' : 'Checkpoint Point',
				'AK160' : 'Stadium Point',
				'AL030' : 'Cemetery Point',
				'AL130' : 'Memorial Monument Point',
				'AK040' : 'Sports Ground Point',
				'AK150' : 'Ski-jump Point',
				'AK170' : 'Swimming Pool Point',
				'BI030' : 'Lock Area',
				'BI030' : 'Lock Line',
				'BI040' : 'Sluice Gate Line',
				'BI030' : 'Lock Point',
				'BI040' : 'Sluice Gate Point',
				'AL025' : 'Cairn Point',
				'SU001' : 'Military Installation Area',
				'AH025' : 'Engineered Earthwork Line',
				'SU001' : 'Military Installation Point',
				'AQ110' : 'Mooring Mast Point',
				'GA034' : 'Aeronautical Radio Navigation Service Point',
				'GB485' : 'Approach Lighting System Point',
				'GB040' : 'Launch Pad Point',
				'GB220' : 'Aeronautical Obstacle Point',
				'BH110' : 'Penstock Line',
				'BI041' : 'Water Gate Line',
				'BI041' : 'Water Gate Point',
				'BI050' : 'Water Intake Tower Point',
				'AL012' : 'Archeological Site Area',
				'AL105' : 'Settlement Area',
				'AL010' : 'Facility Area',
				'AL019' : 'Shed Area',
				'AJ110' : 'Greenhouse Area',
				'AL012' : 'Archeological Site Point',
				'AL105' : 'Settlement Point',
				'AL099' : 'Hut Point',
				'AJ110' : 'Greenhouse Point',
				'AL019' : 'Shed Point',
				'DB029' : 'Cave Mouth Point',
				'DB150' : 'Mountain Pass Point',
				'AL140' : 'Particle Accelerator Area',
				'EC020' : 'Oasis Area',
				'AF010' : 'Smokestack Point',
				'AF040' : 'Crane Point',
				'AF070' : 'Flare Pipe Point',
				'AJ050' : 'Windmill Point',
				'DB180' : 'Volcano Area',
				'AK190' : 'Recreational Pier Area',
				'BB190' : 'Berthing Structure Area',
				'AK190' : 'Recreational Pier Line',
				'BB190' : 'Berthing Structure Line',
				'AQ113' : 'Pipeline Line',
				'AL170' : 'Public Square Area',
				'AD010' : 'Electric Power Station Area',
				'AD050' : 'Heating Facility Area',
				'AT030' : 'Power Line Line',
				'AT041' : 'Cableway Line',
				'AD010' : 'Electric Power Station Point',
				'AD020' : 'Solar Panel Point',
				'AD050' : 'Heating Facility Point',
				'AC000' : 'Processing Facility Area',
				'AC000' : 'Processing Facility Point',
				'AA052' : 'Hydrocarbons Field Area',
				'AQ116' : 'Pumping Station Area',
				'AQ116' : 'Pumping Station Point',
				'AN010' : 'Railway Line',
				'AN050' : 'Railway Sidetrack Line',
				'BB240' : 'Slipway Area',
				'BH120' : 'Rapids Area',
				'BH120' : 'Rapids Line',
				'BH180' : 'Waterfall Line',
				'BH120' : 'Rapids Point',
				'BH145' : 'Vanishing Point Point',
				'BH180' : 'Waterfall Point',
				'AA040' : 'Rig Point',
				'AC020' : 'Catalytic Cracker Point',
				'AP030' : 'Road Line',
				'AN075' : 'Railway Turntable Point',
				'AN060' : 'Railway Yard Area',
				'AL200' : 'Ruins Area',
				'GB015' : 'Apron Area',
				'GB045' : 'Stopway Area',
				'GB055' : 'Runway Area',
				'GB075' : 'Taxiway Area',
				'GB050' : 'Aircraft Revetment Line',
				'GB050' : 'Aircraft Revetment Point',
				'BB041' : 'Breakwater Area',
				'BB043' : 'Groin Area',
				'BB140' : 'Training Wall Area',
				'BB041' : 'Breakwater Line',
				'BB043' : 'Groin Line',
				'BB140' : 'Training Wall Line',
				'BB230' : 'Seawall Line',
				'AL210' : 'Protection Shed Line',
				'AL210' : 'Protection Shed Point',
				'AK090' : 'Fairground Area',
				'AK100' : 'Golf Course Area',
				'AM010' : 'Storage Depot Area',
				'AM040' : 'Mineral Pile Area',
				'AM060' : 'Surface Bunker Area',
				'AM070' : 'Storage Tank Area',
				'AM040' : 'Mineral Pile Point',
				'AM060' : 'Surface Bunker Point',
				'AM070' : 'Storage Tank Point',
				'AD030' : 'Power Substation Area',
				'AD030' : 'Power Substation Point',
				'BH015' : 'Bog Area',
				'ED010' : 'Marsh Area',
				'ED020' : 'Swamp Area',
				'ED030' : 'Mangrove Swamp Area',
				'AT060' : 'Communication Line Line',
				'FA100' : 'Test Site Area',
				'ZD040' : 'Named Location Point',
				'DB115' : 'Geothermal Outlet Area',
				'DB115' : 'Geothermal Outlet Point',
				'DB180' : 'Volcano Point',
				'AL241' : 'Tower Point',
				'AP010' : 'Cart Track Line',
				'AP050' : 'Trail Line',
				'AQ125' : 'Transportation Station Area',
				'AQ135' : 'Roadside Rest Area Area',
				'AQ140' : 'Vehicle Lot Area',
				'AL060' : 'Dragon\'s Teeth Area',
				'AN076' : 'Roundhouse Area',
				'AL060' : 'Dragon\'s Teeth Line',
				'AQ090' : 'Entrance and/or Exit Point',
				'AQ125' : 'Transportation Station Point',
				'AQ065' : 'Culvert Point',
				'AN076' : 'Roundhouse Point',
				'AC030' : 'Settling Pond Area',
				'AJ030' : 'Holding Pen Area',
				'BH040' : 'Water Treatment Bed Area',
				'BH050' : 'Mariculture Site Area',
				'BH051' : 'Fish Farm Facility Area',
				'AC030' : 'Settling Pond Point',
				'AJ030' : 'Holding Pen Point',
				'EC030' : 'Wood Area',
				'EA020' : 'Hedgerow Line',
				'EC030' : 'Wood Line',
				'EC030' : 'Wood Point',
				'BJ110' : 'Tundra Area',
				'AQ130' : 'Tunnel Area',
				'AQ130' : 'Tunnel Line',
				'AJ051' : 'Wind Turbine Point',
				'AT042' : 'Pylon Point',
				'ZD020' : 'Void Collection Area Area',
				'BH020' : 'Canal Area',
				'BH030' : 'Ditch Area',
				'BH140' : 'River Area',
				'BH020' : 'Canal Line',
				'BH030' : 'Ditch Line',
				'BH140' : 'River Line',
				'AA050' : 'Well Point',
				'BH170' : 'Natural Pool Point',
				'ZD040' : 'Named Location Line',
				'ZD045' : 'Annotated Location Line',
				'ZD045' : 'Annotated Location Point',
				'ZD040' : 'Named Location Point',
				'CA010' : 'Elevation Contour Line',
				'CA030' : 'Spot Elevation Point',
				'CA035' : 'Inland Water Elevation Point',
				'ZB050' : 'Survey Point',
				'FA002' : 'Geopolitical Entity Area',
				'FA003' : 'Administrative Division Area',
				'FA000' : 'Administrative Boundary Line',
				'FA110' : 'International Date Line Line',
				'FC021' : 'Maritime Limit Boundary Line'
}

fcsub_dict = { 0 : 'Land Aerodrome Area',
				1 : 'Heliport Area',
				2 : 'Water Aerodrome Area',
				3 : 'Aircraft Hangar Area',
				0 : 'Helipad Point',
				2 : 'Water Aerodrome Point',
				3 : 'Aircraft Hangar Point',
				0 : 'Grain Storage Structure Area',
				1 : 'Grain Elevator Area',
				0 : 'Grain Storage Structure Point',
				1 : 'Grain Elevator Point',
				0 : 'Aqueduct Area',
				0 : 'Aqueduct Line',
				0 : 'Aqueduct Point',
				0 : 'Fence Line',
				1 : 'Wall Line',
				0 : 'Steep Terrain Face Line',
				0 : 'Bridge Area',
				0 : 'Bridge Line',
				0 : 'General Building Area',
				0 : 'General Building Point',
				0 : 'Built-Up Area Area',
				1 : 'Shanty Town Area',
				0 : 'Built-Up Area Point',
				0 : 'Cistern Point',
				0 : 'Island Area',
				1 : 'Tidal Water Area',
				2 : 'Beach Area',
				0 : 'Land Water Boundary Line',
				0 : 'Beach Point',
				0 : 'Communication Station Area',
				0 : 'Dish Aerial Point',
				1 : 'Radar Station Point',
				0 : 'Rice Field Area',
				1 : 'Crop Land Area',
				2 : 'Orchard Area',
				3 : 'Vineyard Area',
				4 : 'Hop Field Area',
				0 : 'Dam Area',
				1 : 'Spillway Area',
				0 : 'Dam Line',
				1 : 'Spillway Line',
				0 : 'Dam Point',
				0 : 'Structural Pile Area',
				1 : 'Reef Area',
				0 : 'Reef Line',
				0 : 'Structural Pile Point',
				1 : 'Offshore Platform Point',
				2 : 'Hazardous Rock Point',
				3 : 'Wreck Point',
				0 : 'Disposal Site Area',
				1 : 'Recycling Site Area',
				0 : 'Embankment Area',
				0 : 'Causeway Structure Line',
				1 : 'Cut Line',
				2 : 'Embankment Line',
				3 : 'Cut Line Line',
				0 : 'Extraction Mine Area',
				1 : 'Quarry Area',
				2 : 'Salt Evaporator Area',
				3 : 'Salt Flat Area',
				0 : 'Extraction Mine Point',
				1 : 'Quarry Point',
				0 : 'Ferry Crossing Line',
				0 : 'Ferry Crossing Point',
				0 : 'Cleared Way Area',
				1 : 'Forest Clearing Area',
				0 : 'Ford Line',
				0 : 'Ford Point',
				0 : 'Fortification Area',
				0 : 'Fortification Point',
				0 : 'Grassland Area',
				1 : 'Thicket Area',
				2 : 'Cane Area',
				0 : 'Soil Surface Region Area',
				0 : 'Harbour Area',
				2 : 'Dry Dock Area',
				0 : 'Maritime Signal Station Point',
				0 : 'Conveyor Line',
				1 : 'Flume Line',
				2 : 'Geophysical Prospecting Grid Line',
				0 : 'Land Subject to Inundation Area',
				0 : 'Lake Area',
				1 : 'Reservoir Area',
				0 : 'Sabkha Area',
				1 : 'Sand Dunes Area',
				0 : 'Moraine Area',
				1 : 'Rock Formation Area',
				0 : 'Gully Area',
				1 : 'Crevasse Area',
				2 : 'Crevice Area',
				0 : 'Ice Cliff Line',
				1 : 'Geologic Fault Line',
				2 : 'Gully Line',
				3 : 'Crevasse Line',
				4 : 'Crevice Line',
				5 : 'Esker Line',
				6 : 'Rock Formation Line',
				0 : 'Ice Peak Point',
				1 : 'Rock Formation Point',
				0 : 'Glacier Area',
				1 : 'Snow Field and/or Ice-field Area',
				0 : 'Circular Irrigation System Area',
				1 : 'Amusement Park Area',
				2 : 'Camp-site Area',
				3 : 'Park Area',
				4 : 'Stadium Area',
				5 : 'Zoo Area',
				6 : 'Cemetery Area',
				7 : 'Sports Ground Area',
				8 : 'Firing Range Area',
				9 : 'Camp Area',
				10 : 'Swimming Pool Area',
				0 : 'Racetrack Line',
				1 : 'Ice Route Line',
				2 : 'Ski-jump Line',
				0 : 'Checkpoint Point',
				1 : 'Stadium Point',
				2 : 'Cemetery Point',
				3 : 'Memorial Monument Point',
				4 : 'Sports Ground Point',
				5 : 'Ski-jump Point',
				6 : 'Swimming Pool Point',
				0 : 'Lock Area',
				0 : 'Lock Line',
				1 : 'Sluice Gate Line',
				0 : 'Lock Point',
				1 : 'Sluice Gate Point',
				0 : 'Cairn Point',
				0 : 'Military Installation Area',
				0 : 'Engineered Earthwork Line',
				0 : 'Military Installation Point',
				1 : 'Mooring Mast Point',
				2 : 'Aeronautical Radio Navigation Service Point',
				3 : 'Approach Lighting System Point',
				4 : 'Launch Pad Point',
				5 : 'Aeronautical Obstacle Point',
				0 : 'Penstock Line',
				1 : 'Water Gate Line',
				0 : 'Water Gate Point',
				1 : 'Water Intake Tower Point',
				0 : 'Archeological Site Area',
				1 : 'Settlement Area',
				2 : 'Facility Area',
				3 : 'Shed Area',
				4 : 'Greenhouse Area',
				0 : 'Archeological Site Point',
				1 : 'Settlement Point',
				2 : 'Hut Point',
				3 : 'Greenhouse Point',
				4 : 'Shed Point',
				0 : 'Cave Mouth Point',
				1 : 'Mountain Pass Point',
				0 : 'Particle Accelerator Area',
				0 : 'Oasis Area',
				0 : 'Smokestack Point',
				2 : 'Crane Point',
				3 : 'Flare Pipe Point',
				4 : 'Windmill Point',
				0 : 'Volcano Area',
				0 : 'Recreational Pier Area',
				1 : 'Berthing Structure Area',
				0 : 'Recreational Pier Line',
				1 : 'Berthing Structure Line',
				0 : 'Pipeline Line',
				0 : 'Public Square Area',
				0 : 'Electric Power Station Area',
				1 : 'Heating Facility Area',
				0 : 'Power Line Line',
				1 : 'Cableway Line',
				0 : 'Electric Power Station Point',
				1 : 'Solar Panel Point',
				2 : 'Heating Facility Point',
				0 : 'Processing Facility Area',
				0 : 'Processing Facility Point',
				0 : 'Hydrocarbons Field Area',
				1 : 'Pumping Station Area',
				0 : 'Pumping Station Point',
				0 : 'Railway Line',
				1 : 'Railway Sidetrack Line',
				0 : 'Slipway Area',
				0 : 'Rapids Area',
				0 : 'Rapids Line',
				1 : 'Waterfall Line',
				0 : 'Rapids Point',
				1 : 'Vanishing Point Point',
				2 : 'Waterfall Point',
				0 : 'Rig Point',
				1 : 'Catalytic Cracker Point',
				0 : 'Road Line',
				0 : 'Railway Turntable Point',
				0 : 'Railway Yard Area',
				0 : 'Ruins Area',
				0 : 'Apron Area',
				1 : 'Stopway Area',
				2 : 'Runway Area',
				3 : 'Taxiway Area',
				0 : 'Aircraft Revetment Line',
				0 : 'Aircraft Revetment Point',
				0 : 'Breakwater Area',
				1 : 'Groin Area',
				2 : 'Training Wall Area',
				0 : 'Breakwater Line',
				1 : 'Groin Line',
				2 : 'Training Wall Line',
				3 : 'Seawall Line',
				0 : 'Protection Shed Line',
				0 : 'Protection Shed Point',
				0 : 'Fairground Area',
				1 : 'Golf Course Area',
				0 : 'Storage Depot Area',
				1 : 'Mineral Pile Area',
				2 : 'Surface Bunker Area',
				3 : 'Storage Tank Area',
				0 : 'Mineral Pile Point',
				1 : 'Surface Bunker Point',
				2 : 'Storage Tank Point',
				0 : 'Power Substation Area',
				0 : 'Power Substation Point',
				0 : 'Bog Area',
				1 : 'Marsh Area',
				2 : 'Swamp Area',
				3 : 'Mangrove Swamp Area',
				0 : 'Communication Line Line',
				0 : 'Test Site Area',
				0 : 'Named Location Point',
				0 : 'Geothermal Outlet Area',
				0 : 'Geothermal Outlet Point',
				1 : 'Volcano Point',
				0 : 'Tower Point',
				0 : 'Cart Track Line',
				0 : 'Trail Line',
				0 : 'Transportation Station Area',
				1 : 'Roadside Rest Area Area',
				2 : 'Vehicle Lot Area',
				3 : 'Dragon\'s Teeth Area',
				4 : 'Roundhouse Area',
				0 : 'Dragon\'s Teeth Line',
				0 : 'Entrance and/or Exit Point',
				1 : 'Transportation Station Point',
				2 : 'Culvert Point',
				3 : 'Roundhouse Point',
				0 : 'Settling Pond Area',
				1 : 'Holding Pen Area',
				2 : 'Water Treatment Bed Area',
				3 : 'Mariculture Site Area',
				4 : 'Fish Farm Facility Area',
				0 : 'Settling Pond Point',
				1 : 'Holding Pen Point',
				0 : 'Wood Area',
				0 : 'Hedgerow Line',
				1 : 'Wood Line',
				0 : 'Wood Point',
				0 : 'Tundra Area',
				0 : 'Tunnel Area',
				0 : 'Tunnel Line',
				0 : 'Wind Turbine Point',
				1 : 'Pylon Point',
				0 : 'Void Collection Area Area',
				0 : 'Canal Area',
				1 : 'Ditch Area',
				2 : 'River Area',
				0 : 'Canal Line',
				1 : 'Ditch Line',
				2 : 'River Line',
				0 : 'Well Point',
				1 : 'Natural Pool Point',
				0 : 'Named Location Line',
				1 : 'Annotated Location Line',
				0 : 'Annotated Location Point',
				1 : 'Named Location Point',
				0 : 'Elevation Contour Line',
				0 : 'Spot Elevation Point',
				1 : 'Inland Water Elevation Point',
				2 : 'Survey Point',
				0 : 'Geopolitical Entity Area',
				1 : 'Administrative Division Area',
				0 : 'Administrative Boundary Line',
				1 : 'International Date Line Line',
				2 : 'Maritime Limit Boundary Line'
}

sub2fcode_dict = { 0 : 'GB005',
					1 : 'GB035',
					2 : 'GB065',
					3 : 'GB230',
					0 : 'GB030',
					2 : 'GB065',
					3 : 'GB230',
					0 : 'AM020',
					1 : 'AM030',
					0 : 'AM020',
					1 : 'AM030',
					0 : 'BH010',
					0 : 'BH010',
					0 : 'BH010',
					0 : 'AL070',
					1 : 'AL260',
					0 : 'DB010',
					0 : 'AQ040',
					0 : 'AQ040',
					0 : 'AL015',
					0 : 'AL015',
					0 : 'AL020',
					1 : 'AL208',
					0 : 'AL020',
					0 : 'BI010',
					0 : 'BA030',
					1 : 'BA040',
					2 : 'BA050',
					0 : 'BA010',
					0 : 'BA050',
					0 : 'AT050',
					0 : 'AT010',
					1 : 'AT045',
					0 : 'BH135',
					1 : 'EA010',
					2 : 'EA040',
					3 : 'EA050',
					4 : 'EA055',
					0 : 'BI020',
					1 : 'BH165',
					0 : 'BI020',
					1 : 'BH165',
					0 : 'BI020',
					0 : 'BD100',
					1 : 'BD120',
					0 : 'BD120',
					0 : 'BD100',
					1 : 'BD110',
					2 : 'BD130',
					3 : 'BD180',
					0 : 'AB000',
					1 : 'AB010',
					0 : 'DB090',
					0 : 'AQ063',
					1 : 'DB070',
					2 : 'DB090',
					3 : 'DB071',
					0 : 'AA010',
					1 : 'AA012',
					2 : 'BH155',
					3 : 'BH150',
					0 : 'AA010',
					1 : 'AA012',
					0 : 'AQ070',
					0 : 'AQ070',
					0 : 'EC040',
					1 : 'EC060',
					0 : 'BH070',
					0 : 'BH070',
					0 : 'AH050',
					0 : 'AH050',
					0 : 'EB010',
					1 : 'EB020',
					2 : 'EC010',
					0 : 'DA010',
					0 : 'BB005',
					2 : 'BB090',
					0 : 'BB155',
					0 : 'AF020',
					1 : 'BH060',
					2 : 'FA090',
					0 : 'BH090',
					0 : 'BH080',
					1 : 'BH130',
					0 : 'BH160',
					1 : 'DB170',
					0 : 'BJ020',
					1 : 'DB160',
					0 : 'DB200',
					1 : 'BJ031',
					2 : 'DB061',
					0 : 'BJ040',
					1 : 'DB110',
					2 : 'DB200',
					3 : 'BJ031',
					4 : 'DB061',
					5 : 'DB100',
					6 : 'DB160',
					0 : 'BJ060',
					1 : 'DB160',
					0 : 'BJ030',
					1 : 'BJ100',
					0 : 'AJ010',
					1 : 'AK030',
					2 : 'AK060',
					3 : 'AK120',
					4 : 'AK160',
					5 : 'AK180',
					6 : 'AL030',
					7 : 'AK040',
					8 : 'FA015',
					9 : 'AI030',
					10 : 'AK170',
					0 : 'AK130',
					1 : 'AQ075',
					2 : 'AK150',
					0 : 'AH070',
					1 : 'AK160',
					2 : 'AL030',
					3 : 'AL130',
					4 : 'AK040',
					5 : 'AK150',
					6 : 'AK170',
					0 : 'BI030',
					0 : 'BI030',
					1 : 'BI040',
					0 : 'BI030',
					1 : 'BI040',
					0 : 'AL025',
					0 : 'SU001',
					0 : 'AH025',
					0 : 'SU001',
					1 : 'AQ110',
					2 : 'GA034',
					3 : 'GB485',
					4 : 'GB040',
					5 : 'GB220',
					0 : 'BH110',
					1 : 'BI041',
					0 : 'BI041',
					1 : 'BI050',
					0 : 'AL012',
					1 : 'AL105',
					2 : 'AL010',
					3 : 'AL019',
					4 : 'AJ110',
					0 : 'AL012',
					1 : 'AL105',
					2 : 'AL099',
					3 : 'AJ110',
					4 : 'AL019',
					0 : 'DB029',
					1 : 'DB150',
					0 : 'AL140',
					0 : 'EC020',
					0 : 'AF010',
					2 : 'AF040',
					3 : 'AF070',
					4 : 'AJ050',
					0 : 'DB180',
					0 : 'AK190',
					1 : 'BB190',
					0 : 'AK190',
					1 : 'BB190',
					0 : 'AQ113',
					0 : 'AL170',
					0 : 'AD010',
					1 : 'AD050',
					0 : 'AT030',
					1 : 'AT041',
					0 : 'AD010',
					1 : 'AD020',
					2 : 'AD050',
					0 : 'AC000',
					0 : 'AC000',
					0 : 'AA052',
					1 : 'AQ116',
					0 : 'AQ116',
					0 : 'AN010',
					1 : 'AN050',
					0 : 'BB240',
					0 : 'BH120',
					0 : 'BH120',
					1 : 'BH180',
					0 : 'BH120',
					1 : 'BH145',
					2 : 'BH180',
					0 : 'AA040',
					1 : 'AC020',
					0 : 'AP030',
					0 : 'AN075',
					0 : 'AN060',
					0 : 'AL200',
					0 : 'GB015',
					1 : 'GB045',
					2 : 'GB055',
					3 : 'GB075',
					0 : 'GB050',
					0 : 'GB050',
					0 : 'BB041',
					1 : 'BB043',
					2 : 'BB140',
					0 : 'BB041',
					1 : 'BB043',
					2 : 'BB140',
					3 : 'BB230',
					0 : 'AL210',
					0 : 'AL210',
					0 : 'AK090',
					1 : 'AK100',
					0 : 'AM010',
					1 : 'AM040',
					2 : 'AM060',
					3 : 'AM070',
					0 : 'AM040',
					1 : 'AM060',
					2 : 'AM070',
					0 : 'AD030',
					0 : 'AD030',
					0 : 'BH015',
					1 : 'ED010',
					2 : 'ED020',
					3 : 'ED030',
					0 : 'AT060',
					0 : 'FA100',
					0 : 'ZD040',
					0 : 'DB115',
					0 : 'DB115',
					1 : 'DB180',
					0 : 'AL241',
					0 : 'AP010',
					0 : 'AP050',
					0 : 'AQ125',
					1 : 'AQ135',
					2 : 'AQ140',
					3 : 'AL060',
					4 : 'AN076',
					0 : 'AL060',
					0 : 'AQ090',
					1 : 'AQ125',
					2 : 'AQ065',
					3 : 'AN076',
					0 : 'AC030',
					1 : 'AJ030',
					2 : 'BH040',
					3 : 'BH050',
					4 : 'BH051',
					0 : 'AC030',
					1 : 'AJ030',
					0 : 'EC030',
					0 : 'EA020',
					1 : 'EC030',
					0 : 'EC030',
					0 : 'BJ110',
					0 : 'AQ130',
					0 : 'AQ130',
					0 : 'AJ051',
					1 : 'AT042',
					0 : 'ZD020',
					0 : 'BH020',
					1 : 'BH030',
					2 : 'BH140',
					0 : 'BH020',
					1 : 'BH030',
					2 : 'BH140',
					0 : 'AA050',
					1 : 'BH170',
					0 : 'ZD040',
					1 : 'ZD045',
					0 : 'ZD045',
					1 : 'ZD040',
					0 : 'CA010',
					0 : 'CA030',
					1 : 'CA035',
					2 : 'ZB050',
					0 : 'FA002',
					1 : 'FA003',
					0 : 'FA000',
					1 : 'FA110',
					2 : 'FC021'
}

# Nested dictionary of feature classes with dictionaries of the subtype codes and matching fcodes within
# Needed for MGCP since FCSubtype values for MGCP aren't unique identifiers for some reason unlike TDS. Makes it needlessly more complicated
sub_cat = { 'AerofacA' : { 0 : 'GB005',
							1 : 'GB035',
							2 : 'GB065',
							3 : 'GB230' },
			'AerofacP' : { 0 : 'GB030',
							2 : 'GB065',
							3 : 'GB230' },
			'AgristrA' : { 0 : 'AM020',
							1 : 'AM030' },
			'AgristrP' : { 0 : 'AM020',
							1 : 'AM030' },
			'AquedctA' : { 0 : 'BH010' },
			'AquedctL' : { 0 : 'BH010' },
			'AquedctP' : { 0 : 'BH010' },
			'BarrierL' : { 0 : 'AL070',
							1 : 'AL260' },
			'BluffL' : { 0 : 'DB010' },
			'BridgeA' : { 0 : 'AQ040' },
			'BridgeL' : { 0 : 'AQ040' },
			'BuildA' : { 0 : 'AL015' },
			'BuildP' : { 0 : 'AL015' },
			'BuiltupA' : { 0 : 'AL020',
							1 : 'AL208' },
			'BuiltupP' : { 0 : 'AL020' },
			'CisternP' : { 0 : 'BI010' },
			'CoastA' : { 0 : 'BA030',
							1 : 'BA040',
							2 : 'BA050' },
			'CoastL' : { 0 : 'BA010' },
			'CoastP' : { 0 : 'BA050' },
			'CommA' : { 0 : 'AT050' },
			'CommP' : { 0 : 'AT010',
							1 : 'AT045' },
			'CropA' : { 0 : 'BH135',
							1 : 'EA010',
							2 : 'EA040',
							3 : 'EA050',
							4 : 'EA055' },
			'DamA' : { 0 : 'BI020',
							1 : 'BH165' },
			'DamL' : { 0 : 'BI020',
							1 : 'BH165' },
			'DamP' : { 0 : 'BI020' },
			'DangerA' : { 0 : 'BD100',
							1 : 'BD120' },
			'DangerL' : { 0 : 'BD120' },
			'DangerP' : { 0 : 'BD100',
							1 : 'BD110',
							2 : 'BD130',
							3 : 'BD180' },
			'DisposeA' : { 0 : 'AB000',
							1 : 'AB010' },
			'EmbankA' : { 0 : 'DB090' },
			'EmbankL' : { 0 : 'AQ063',
							1 : 'DB070',
							2 : 'DB090',
							3 : 'DB071' },
			'ExtractA' : { 0 : 'AA010',
							1 : 'AA012',
							2 : 'BH155',
							3 : 'BH150' },
			'ExtractP' : { 0 : 'AA010',
							1 : 'AA012' },
			'FerryL' : { 0 : 'AQ070' },
			'FerryP' : { 0 : 'AQ070' },
			'FirebrkA' : { 0 : 'EC040',
							1 : 'EC060' },
			'FordL' : { 0 : 'BH070' },
			'FordP' : { 0 : 'BH070' },
			'FortA' : { 0 : 'AH050' },
			'FortP' : { 0 : 'AH050' },
			'GrassA' : { 0 : 'EB010',
							1 : 'EB020',
							2 : 'EC010' },
			'GroundA' : { 0 : 'DA010' },
			'HarborA' : { 0 : 'BB005',
							2 : 'BB090' },
			'HarborP' : { 0 : 'BB155' },
			'IndL' : { 0 : 'AF020',
							1 : 'BH060',
							2 : 'FA090' },
			'InundA' : { 0 : 'BH090' },
			'LakeresA' : { 0 : 'BH080',
							1 : 'BH130' },
			'Landfrm1A' : { 0 : 'BH160',
							1 : 'DB170' },
			'Landfrm2A' : { 0 : 'BJ020',
							1 : 'DB160' },
			'LandfrmA' : { 0 : 'DB200',
							1 : 'BJ031',
							2 : 'DB061' },
			'LandfrmL' : { 0 : 'BJ040',
							1 : 'DB110',
							2 : 'DB200',
							3 : 'BJ031',
							4 : 'DB061',
							5 : 'DB100',
							6 : 'DB160' },
			'LandfrmP' : { 0 : 'BJ060',
							1 : 'DB160' },
			'LandIceA' : { 0 : 'BJ030',
							1 : 'BJ100' },
			'LandmrkA' : { 0 : 'AJ010',
							1 : 'AK030',
							2 : 'AK060',
							3 : 'AK120',
							4 : 'AK160',
							5 : 'AK180',
							6 : 'AL030',
							7 : 'AK040',
							8 : 'FA015',
							9 : 'AI030',
							10 : 'AK170' },
			'LandmrkL' : { 0 : 'AK130',
							1 : 'AQ075',
							2 : 'AK150' },
			'LandmrkP' : { 0 : 'AH070',
							1 : 'AK160',
							2 : 'AL030',
							3 : 'AL130',
							4 : 'AK040',
							5 : 'AK150',
							6 : 'AK170' },
			'LockA' : { 0 : 'BI030' },
			'LockL' : { 0 : 'BI030',
							1 : 'BI040' },
			'LockP' : { 0 : 'BI030',
							1 : 'BI040' },
			'MarkersP' : { 0 : 'AL025' },
			'MilA' : { 0 : 'SU001' },
			'MilL' : { 0 : 'AH025' },
			'MilP' : { 0 : 'SU001' },
			'MiscaeroP' : { 1 : 'AQ110',
							2 : 'GA034',
							3 : 'GB485',
							4 : 'GB040',
							5 : 'GB220' },
			'MiscL' : { 0 : 'BH110',
							1 : 'BI041' },
			'MiscP' : { 0 : 'BI041',
							1 : 'BI050' },
			'MiscpopA' : { 0 : 'AL012',
							1 : 'AL105',
							2 : 'AL010',
							3 : 'AL019',
							4 : 'AJ110' },
			'MiscpopP' : { 0 : 'AL012',
							1 : 'AL105',
							2 : 'AL099',
							3 : 'AJ110',
							4 : 'AL019' },
			'MtnP' : { 0 : 'DB029',
							1 : 'DB150' },
			'NuclearA' : { 0 : 'AL140' },
			'OasisA' : { 0 : 'EC020' },
			'ObstrP' : { 0 : 'AF010',
							2 : 'AF040',
							3 : 'AF070',
							4 : 'AJ050' },
			'PhysA' : { 0 : 'DB180' },
			'PierA' : { 0 : 'AK190',
							1 : 'BB190' },
			'PierL' : { 0 : 'AK190',
							1 : 'BB190' },
			'PipeL' : { 0 : 'AQ113' },
			'PlazaA' : { 0 : 'AL170' },
			'PowerA' : { 0 : 'AD010',
							1 : 'AD050' },
			'PowerL' : { 0 : 'AT030',
							1 : 'AT041' },
			'PowerP' : { 0 : 'AD010',
							1 : 'AD020',
							2 : 'AD050' },
			'ProcessA' : { 0 : 'AC000' },
			'ProcessP' : { 0 : 'AC000' },
			'PumpingA' : { 0 : 'AA052',
							1 : 'AQ116' },
			'PumpingP' : { 0 : 'AQ116' },
			'RailrdL' : { 0 : 'AN010',
							1 : 'AN050' },
			'RampA' : { 0 : 'BB240' },
			'RapidsA' : { 0 : 'BH120' },
			'RapidsL' : { 0 : 'BH120',
							1 : 'BH180' },
			'RapidsP' : { 0 : 'BH120',
							1 : 'BH145',
							2 : 'BH180' },
			'RigwellP' : { 0 : 'AA040',
							1 : 'AC020' },
			'RoadL' : { 0 : 'AP030' },
			'RrturnP' : { 0 : 'AN075' },
			'RryardA' : { 0 : 'AN060' },
			'RuinsA' : { 0 : 'AL200' },
			'RunwayA' : { 0 : 'GB015',
							1 : 'GB045',
							2 : 'GB055',
							3 : 'GB075' },
			'RunwayL' : { 0 : 'GB050' },
			'RunwayP' : { 0 : 'GB050' },
			'SeastrtA' : { 0 : 'BB041',
							1 : 'BB043',
							2 : 'BB140' },
			'SeastrtL' : { 0 : 'BB041',
							1 : 'BB043',
							2 : 'BB140',
							3 : 'BB230' },
			'ShedL' : { 0 : 'AL210' },
			'ShedP' : { 0 : 'AL210' },
			'SportA' : { 0 : 'AK090',
							1 : 'AK100' },
			'StorageA' : { 0 : 'AM010',
							1 : 'AM040',
							2 : 'AM060',
							3 : 'AM070' },
			'StorageP' : { 0 : 'AM040',
							1 : 'AM060',
							2 : 'AM070' },
			'SubstatA' : { 0 : 'AD030' },
			'SubstatP' : { 0 : 'AD030' },
			'SwampA' : { 0 : 'BH015',
							1 : 'ED010',
							2 : 'ED020',
							3 : 'ED030' },
			'TeleL' : { 0 : 'AT060' },
			'TestA' : { 0 : 'FA100' },
			'TextP' : { 0 : 'ZD040' },
			'ThermalA' : { 0 : 'DB115' },
			'ThermalP' : { 0 : 'DB115',
							1 : 'DB180' },
			'TowerP' : { 0 : 'AL241' },
			'TrackL' : { 0 : 'AP010' },
			'TrailL' : { 0 : 'AP050' },
			'TransA' : { 0 : 'AQ125',
							1 : 'AQ135',
							2 : 'AQ140',
							3 : 'AL060',
							4 : 'AN076' },
			'TransL' : { 0 : 'AL060' },
			'TransP' : { 0 : 'AQ090',
							1 : 'AQ125',
							2 : 'AQ065',
							3 : 'AN076' },
			'TreatA' : { 0 : 'AC030',
							1 : 'AJ030',
							2 : 'BH040',
							3 : 'BH050',
							4 : 'BH051' },
			'TreatP' : { 0 : 'AC030',
							1 : 'AJ030' },
			'TreesA' : { 0 : 'EC030' },
			'TreesL' : { 0 : 'EA020',
							1 : 'EC030' },
			'TreesP' : { 0 : 'EC030' },
			'TundraA' : { 0 : 'BJ110' },
			'TunnelA' : { 0 : 'AQ130' },
			'TunnelL' : { 0 : 'AQ130' },
			'UtilP' : { 0 : 'AJ051',
							1 : 'AT042' },
			'VoidA' : { 0 : 'ZD020' },
			'WatrcrsA' : { 0 : 'BH020',
							1 : 'BH030',
							2 : 'BH140' },
			'WatrcrsL' : { 0 : 'BH020',
							1 : 'BH030',
							2 : 'BH140' },
			'WellsprP' : { 0 : 'AA050',
							1 : 'BH170' },
			'AnnoL' : { 0 : 'ZD040',
							1 : 'ZD045' },
			'AnnoP' : { 0 : 'ZD045',
							1 : 'ZD040' },
			'ContourL' : { 0 : 'CA010' },
			'ElevP' : { 0 : 'CA030',
							1 : 'CA035',
							2 : 'ZB050' },
			'PolbndA' : { 0 : 'FA002',
							1 : 'FA003' },
			'PolbndL' : { 0 : 'FA000',
							1 : 'FA110',
							2 : 'FC021' }
}


# User parameters
MGCP = arcpy.GetParameterAsText(0)
arcpy.env.workspace = MGCP
arcpy.env.overwriteOutput = True
arcpy.RefreshCatalog(MGCP)
featureclass = arcpy.ListFeatureClasses()
featureclass.sort()

''''''''' Repair Topology '''''''''

# Repairs the geometry of all feature classes for any NULL geometries left behind after validating a Topology
# for fc in featureclass:
# 	write("Repairing NULL geometries from Topology in " + str(fc))
# 	arcpy.RepairGeometry_management(fc, "DELETE_NULL")


''''''''' Populate F_Code '''''''''

# Modified John's Fcode tool to work with nest MGCP subtype Dictionary
for fc in featureclass:
	#try:
	with arcpy.da.UpdateCursor(fc,["f_code", "fcsubtype"]) as ucursor:
		for i in ucursor:
			if i[0] != str(sub_cat[fc][i[1]]):
				i[0] = str(sub_cat[fc][i[1]])
				ucursor.updateRow(i)
	write(str(fc) + " Feature F_Codes updated")
	#except:
		#write(str(fc) + " does not contain F_Codes.")
write("\n")


''''''''' Simple Explode All Multipart '''''''''

single = "in_memory\\single"
for fc in featureclass:
	write("Exploding multipart features in {0}".format(fc))
	arcpy.MultipartToSinglepart_management(fc, single)
	arcpy.DeleteFeatures_management(fc)
	arcpy.Append_management(single, fc, "NO_TEST", "", "")
	arcpy.Delete_management(single)
write("\n")


''''''''' Make Feature Layers '''''''''

# Make feature layers for each fc
write("Making Feature Layers")
write("PowerP")
arcpy.MakeFeatureLayer_management("PowerP", "power_p")
write("SubstatP")
arcpy.MakeFeatureLayer_management("SubstatP", "substat_p")
write("UtilP")
arcpy.MakeFeatureLayer_management("UtilP", "util_p")
write("PipeL")
arcpy.MakeFeatureLayer_management("PipeL", "pipe_l")
write("PowerL")
arcpy.MakeFeatureLayer_management("PowerL", "power_l")
write("TeleL")
arcpy.MakeFeatureLayer_management("TeleL", "tele_l")
write("PowerA")
arcpy.MakeFeatureLayer_management("PowerA", "power_a")
write("SubstatA")
arcpy.MakeFeatureLayer_management("SubstatA", "substation_a")
write("\n")


''''''''' Calculate Default Values '''''''''

# Calculate Default Values
write("Calculating Default Values")
arcpy.CalculateDefaultValues_defense(arcpy.env.workspace)
write("\n")


''''''''' Calculate Metrics '''''''''
# # Calculates the metric values of the specified fields
# tool_name = 'Calculate Metrics'
# metric_type = 'LENGTH;WIDTH;AREA'
# for fc in featureclass:
# 	try:
# 		arcpy.AddMessage("Calculating AOO, ARA, LZN, and WID for " + str(fc))
# 		arcpy.CalculateMetrics_defense(fc, metric_type, "LZN", "WID", "ARA", "#", "#", "#")
# 		arcpy.CalculateMetrics_defense
# 	except arcpy.ExecuteError:
# 		# if the code failed for the current fc, check the error
# 		write("\n***Failed to run {0}.***\n".format(tool_name))
# 		write("Error Report:")
# 		write("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
# 		write(arcpy.GetMessages())
# 		write("~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~")
# 		sys.exit(0)


''''''''' Integrate and Repair '''''''''

# Integrating Utility surfaces and points to curves
write("Integrating Utilities")
arcpy.Integrate_management("power_p 2;substat_p 2;util_p 2;pipe_l 1;power_l 1;tele_l 1;power_a 3;substation_a 3", "0.03 Meters")
write("")

# Post Integration Repair
write("Repairing Lines")
arcpy.RepairGeometry_management("pipe_l", "DELETE_NULL")
arcpy.RepairGeometry_management("power_l", "DELETE_NULL")
arcpy.RepairGeometry_management("tele_l", "DELETE_NULL")
write("\n")


''''''''' Repair for Good Measure '''''''''
for fc in featureclass:
	write("Repairing NULL geometries again in " + str(fc))
	arcpy.RepairGeometry_management(fc, "DELETE_NULL")
